<a href="https://colab.research.google.com/github/Rathachai/DA-LAB/blob/gh-pages/code/CH-09/model-based-recsys.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analytics Book : CODE

**ISBN** : 978-616-338-169-9

**Author** : Rathachai Chawuthai

**Year** : 2022

**Copyright** © by KMITL

**Link** : https://github.com/Rathachai/DA-LAB



---

## **Chapter 9 : Recommender System**


---

In [1]:
import numpy as np

In [2]:
# Rating Matrix (-1 means no rating)

R = np.array([
    [ 2, -1, -1,  2,  2],
    [-1,  4,  4, -1,  3],
    [ 1,  4,  1,  2,  2],
    [-1,  2, -1, -1,  5],
    [-1,  2,  1, -1,  5]])

In [3]:
# Set the shape of data

num_users, num_items = R.shape
num_features = 2

In [4]:
# Mean

m = R[R>-1].mean()

In [5]:
# Randomly initial variables

BI = np.random.rand(num_items)
BU = np.random.rand(num_users)
Q = np.random.rand(num_features, num_items)
P = np.random.rand(num_features, num_users)

In [6]:
# Check initial variables

print('BI = ', BI)
print('-----------------------')
print('BU = ', BU)
print('-----------------------')
print('Q = ')
print(Q)
print('-----------------------')
print('P = ')
print(P)

BI =  [0.92409232 0.37582964 0.15784256 0.86406983 0.61428513]
-----------------------
BU =  [0.91518722 0.17707827 0.37717357 0.99528889 0.10888368]
-----------------------
Q = 
[[0.99285724 0.55309625 0.38595235 0.16601081 0.90172046]
 [0.2278401  0.62149473 0.74428592 0.61561853 0.53398909]]
-----------------------
P = 
[[0.27825837 0.04776916 0.56843267 0.40766324 0.02668244]
 [0.81374309 0.8788218  0.02602903 0.91730251 0.04688133]]


In [7]:
# Verify initial MAE

R_pred = m + BI[np.newaxis,:] + BU[:,np.newaxis] + P.T.dot(Q)
mae = abs(R[R>0]-R_pred[R>0]).mean()
print(mae)

1.7591445798829657


In [8]:
#set learning rate
alpha = 0.1

#set number of epoch
epoch_num = 30

In [9]:
for epoch in range(epoch_num):
  for u,i in np.argwhere(R>-1):
    # predict the r^
    r_pred = m + BI[i] + BU[u] + P[:,u].T.dot(Q[:,i])

    # traning
    BI[i] = BI[i] - alpha*(r_pred-R[u,i])
    BU[u] = BU[u] - alpha*(r_pred-R[u,i])
    Q[:,i] = Q[:,i] - alpha*(r_pred-R[u,i])*P[:,u]
    P[:,u] = P[:,u] - alpha*(r_pred-R[u,i])*Q[:,i]

In [10]:
# Check trained variables

print('BI = ', BI)
print('-----------------------')
print('BU = ', BU)
print('-----------------------')
print('Q = ')
print(Q)
print('-----------------------')
print('P = ')
print(P)

BI =  [-0.28038055  0.55690706 -0.74696832 -0.10316328  0.84820625]
-----------------------
BU =  [-0.36309542  0.6220034  -0.23269254  0.12496504 -0.23908716]
-----------------------
Q = 
[[ 0.80082371 -1.03197899 -0.0393756   0.30551432  1.58308232]
 [ 0.65235491 -0.26820193  1.20471192  0.06012455 -0.23567422]]
-----------------------
P = 
[[-0.59028375 -0.50836851 -0.87399258  1.02344977  1.04228741]
 [ 0.67074918  1.23129131 -0.56809087  0.93672368 -0.49606976]]


In [11]:
# Predicted the Rating Matrix

R_PRED = m + BI[np.newaxis,:] + BU[:,np.newaxis] + P.T.dot(Q)

print(R_PRED.round(1))

[[1.9 3.2 2.3 2.  2. ]
 [3.4 4.  4.  3.1 3. ]
 [1.  4.  1.  2.  2. ]
 [3.9 2.  3.1 3.  5. ]
 [2.6 2.  1.  2.6 5. ]]


In [12]:
# Verify MAE after training

mae = np.abs(R[R>0]-R_PRED[R>0]).mean()
print(mae)

0.010660513186119547




---



https://rathachai.creatier.pro/